function fixationsPerTrial = findFixationsPerTrial(filepath, T3data)
video.pixels.height = 1080;
video.pixels.width = 1920;
video.scaling = 2/3;
screen.pixels.height = 1080;
screen.pixels.width = 1920;
videoRelativeRoiMap = aspl.convertToRoiMap(T3data, video.pixels);
avSpeechResults = aspl.parseAvSpeechEyetrackingOutput(aspl.File(filepath));
fixationThreshold_us = 90000;
for trial = 1:numel(avSpeechResults.trial)
    avSpeechTrialResults = avSpeechResults.trial(trial);
    roi = videoRelativeRoiMap(aspl.convertToRoiMapKey(avSpeechTrialResults.target.char));
    fixationsPerTrial(trial).face = aspl.findFixations(...
        avSpeechTrialResults.eyetracking.gaze, ...
        aspl.screenRelativeRegion(screen, video, roi.face), ...
        fixationThreshold_us);
    fixationsPerTrial(trial).upperFace = aspl.findFixations(...
        avSpeechTrialResults.eyetracking.gaze, ...
        aspl.screenRelativeRegion(screen, video, roi.upperFace), ...
        fixationThreshold_us);
    fixationsPerTrial(trial).lowerFace = aspl.findFixations(...
        avSpeechTrialResults.eyetracking.gaze, ...
        aspl.screenRelativeRegion(screen, video, roi.lowerFace), ...
        fixationThreshold_us);
    for leftFixation = 1:numel(fixationsPerTrial(trial).face.left)
        fixationsPerTrial(trial).face.left(leftFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).face.left(leftFixation).firstGazeIndex).time_us);
    end
    for leftFixation = 1:numel(fixationsPerTrial(trial).upperFace.left)
        fixationsPerTrial(trial).upperFace.left(leftFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).upperFace.left(leftFixation).firstGazeIndex).time_us);
    end
    for leftFixation = 1:numel(fixationsPerTrial(trial).lowerFace.left)
        fixationsPerTrial(trial).lowerFace.left(leftFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).lowerFace.left(leftFixation).firstGazeIndex).time_us);
    end
    for rightFixation = 1:numel(fixationsPerTrial(trial).face.right)
        fixationsPerTrial(trial).face.right(rightFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).face.right(rightFixation).firstGazeIndex).time_us);
    end
    for rightFixation = 1:numel(fixationsPerTrial(trial).upperFace.right)
        fixationsPerTrial(trial).upperFace.right(rightFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).upperFace.right(rightFixation).firstGazeIndex).time_us);
    end
    for rightFixation = 1:numel(fixationsPerTrial(trial).lowerFace.right)
        fixationsPerTrial(trial).lowerFace.right(rightFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).lowerFace.right(rightFixation).firstGazeIndex).time_us);
    end
end
end