function fixationsPerTrial = findFixationsPerTrial(filepath, T3data)
video.pixels.height = 1080;
video.pixels.width = 1920;
video.scaling = 2/3;
screen.pixels.height = 1080;
screen.pixels.width = 1920;
videoRelativeRoiMap = aspl.convertToRoiMap(T3data, video.pixels);
avSpeechResults = aspl.parseAvSpeechEyetrackingOutput(aspl.File(filepath));
fixationThreshold_us = 90000;
wholeRegion.x = 0;
wholeRegion.y = 0;
wholeRegion.width = 1;
wholeRegion.height = 1;
for trial = 1:numel(avSpeechResults.trial)
    avSpeechTrialResults = avSpeechResults.trial(trial);
    eyetrackingResults = avSpeechTrialResults.eyetracking;
    roi = videoRelativeRoiMap(aspl.convertToRoiMapKey(avSpeechTrialResults.target.char));
    fixationsPerTrial(trial).face = findFixations(...
        eyetrackingResults, ...
        aspl.screenRelativeRegion(screen, video, roi.face), ...
        fixationThreshold_us);
    fixationsPerTrial(trial).upperFace = findFixations(...
        eyetrackingResults, ...
        aspl.screenRelativeRegion(screen, video, roi.upperFace), ...
        fixationThreshold_us);
    fixationsPerTrial(trial).lowerFace = findFixations(...
        eyetrackingResults, ...
        aspl.screenRelativeRegion(screen, video, roi.lowerFace), ...
        fixationThreshold_us);
    fixationsPerTrial(trial).screen = findFixations(...
        eyetrackingResults, ...
        wholeRegion, ...
        fixationThreshold_us);
    fixationsPerTrial(trial).video = findFixations(...
        eyetrackingResults, ...
        aspl.screenRelativeRegion(screen, video, wholeRegion), ...
        fixationThreshold_us);
end
end

function fixations = findFixations(eyetrackingResults, roi, threshold_us)
fixations = aspl.findFixations(eyetrackingResults.gaze, roi, threshold_us);
fixations.left = addTargetStartTimes(fixations.left, eyetrackingResults);
fixations.right = addTargetStartTimes(fixations.right, eyetrackingResults);
fixations.both = addTargetStartTimes(fixations.both, eyetrackingResults);
end

function fixations = addTargetStartTimes(fixations, eyetrackingResults)
    for i = 1:numel(fixations)
        fixations(i).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            eyetrackingResults, ...
            eyetrackingResults.gaze(fixations(i).firstGazeIndex).time_us);
    end
end