function fixationsPerTrial = findFixationsPerTrial(filepath, T3data)
video.pixels.height = 1080;
video.pixels.width = 1920;
video.scaling = 2/3;
screen.pixels.height = 1080;
screen.pixels.width = 1920;
videoRelativeRoiMap = aspl.convertToRoiMap(T3data, video.pixels);
avSpeechResults = aspl.parseAvSpeechEyetrackingOutput(aspl.File(filepath));
fixationThreshold_us = 90000;
for trial = 1:numel(avSpeechResults.trial)
    avSpeechTrialResults = avSpeechResults.trial(trial);
    fixationsPerTrial(trial) = aspl.findFixations(...
        avSpeechTrialResults.eyetracking.gaze, ...
        aspl.screenRelativeRegion(screen, video, ...
            videoRelativeRoiMap(aspl.convertToRoiMapKey(avSpeechTrialResults.target.char)).face), ...
        fixationThreshold_us);
    for leftFixation = 1:numel(fixationsPerTrial(trial).left)
        fixationsPerTrial(trial).left(leftFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).left(leftFixation).firstGazeIndex).time_us);
    end
    for rightFixation = 1:numel(fixationsPerTrial(trial).right)
        fixationsPerTrial(trial).right(rightFixation).targetStartRelativeTime_ms = aspl.targetStartRelativeTime_ms(...
            avSpeechTrialResults.eyetracking, ...
            avSpeechTrialResults.eyetracking.gaze(...
                fixationsPerTrial(trial).right(rightFixation).firstGazeIndex).time_us);
    end
end
end